### ISSUE TITLE
googleapiclient.errors.HttpError: <HttpError 500 when requesting https://www.googleapis.com/language/translate/v2 returned "Internal Error">

### ISSUE THREAD

**Issue by teolemon** [ankitpopli1891/django-autotranslate#14]
Got this error due to a 500 error

```
MacBook-Air-3:jobmind pierreslam$ ./manage.py translate_messages -u -l de
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autotranslate/management/commands/translate_messages.py", line 69, in handle
    self.translate_file(root, file, target_language)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autotranslate/management/commands/translate_messages.py", line 87, in translate_file
    translated_strings = translate_strings(strings, target_language, 'en', False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autotranslate/services.py", line 90, in translate_strings
    target_language, source_language, optimized)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autotranslate/services.py", line 90, in translate_strings
    target_language, source_language, optimized)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autotranslate/services.py", line 90, in translate_strings
    target_language, source_language, optimized)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autotranslate/services.py", line 90, in translate_strings
    target_language, source_language, optimized)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autotranslate/services.py", line 90, in translate_strings
    target_language, source_language, optimized)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autotranslate/services.py", line 90, in translate_strings
    target_language, source_language, optimized)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autotranslate/services.py", line 90, in translate_strings
    target_language, source_language, optimized)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autotranslate/services.py", line 88, in translate_strings
    self.translate_strings(strings[0:self.max_segments], target_language, source_language, optimized)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autotranslate/services.py", line 84, in translate_strings
    .list(source=source_language, target=target_language, q=strings).execute()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/googleapiclient/http.py", line 723, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 500 when requesting https://www.googleapis.com/language/translate/v2 returned "Internal Error">
```

**Comment by teolemon** [comment]
Tried a second time
`googleapiclient.errors.HttpError: <HttpError 500 when requesting https://www.googleapis.com/language/translate/v2 returned "Backend Error">`
