### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by cedricwebisoft** [ankitpopli1891/django-autotranslate#23]
python --version : Python 3.6.8
python manage.py --version :  2.2

output of python manage.py translate_messages

```
    Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.venv/lib/python3.6/site-packages/autotranslate/management/commands/translate_messages.py", line 76, in handle
    self.translate_file(root, file, target_language)
  File "/home/vagrant/.venv/lib/python3.6/site-packages/autotranslate/management/commands/translate_messages.py", line 96, in translate_file
    translated_strings = tl.translate_strings(strings, target_language, 'en', False)
  File "/home/vagrant/.venv/lib/python3.6/site-packages/autotranslate/services.py", line 46, in translate_strings
    return translations if optimized else [_ for _ in translations]
  File "/home/vagrant/.venv/lib/python3.6/site-packages/autotranslate/services.py", line 46, in <listcomp>
    return translations if optimized else [_ for _ in translations]
  File "/home/vagrant/.venv/lib/python3.6/site-packages/goslate.py", line 441, in <genexpr>
    return (_unwrapper_single_element(i) for i in
  File "/home/vagrant/.venv/lib/python3.6/site-packages/goslate.py", line 215, in _execute
    raise exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vagrant/.venv/lib/python3.6/site-packages/goslate.py", line 435, in task
    r = self._translate_single_text(text, target_language, source_language)
  File "/home/vagrant/.venv/lib/python3.6/site-packages/goslate.py", line 334, in _translate_single_text
    results = list(self._execute(make_task(i) for i in split_text(text)))
  File "/home/vagrant/.venv/lib/python3.6/site-packages/goslate.py", line 203, in _execute
    yield each()
  File "/home/vagrant/.venv/lib/python3.6/site-packages/goslate.py", line 332, in <lambda>
    return lambda: self._basic_translate(text, target_language, source_lauguage)[0]
  File "/home/vagrant/.venv/lib/python3.6/site-packages/goslate.py", line 253, in _basic_translate
    data = {'src': raw_data[-1][0][0]}
IndexError: list index out of range

```

**Comment by saadSarwar28** [comment]
I am facing the same issue. Any updates?

**Comment by geweb7** [comment]
The issue is not resolved
Python 3.6.9
django-autotranslate==1.1.1

https://github.com/zhuoqiang/goslate seems not working any more

**Comment by Joaxin** [comment]
I am facing the same issue as well with py3.7 and dj3.08

**Comment by elMor3no** [comment]
Same issue here.... #29
