### ISSUE TITLE
Django autotranslate installation fails

### ISSUE THREAD

**Issue by cosmosgenius** [ankitpopli1891/django-autotranslate#25]
```
Collecting django-autotranslate
  Using cached django-autotranslate-1.1.0.tar.gz (8.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/sharat/.virtualenvs/mycroft/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lw/n4rl9vm16t38zzv2x_kl74xc0000gn/T/pip-install-y2vmq72u/django-autotranslate/setup.py'"'"'; __file__='"'"'/private/var/folders/lw/n4rl9vm16t38zzv2x_kl74xc0000gn/T/pip-install-y2vmq72u/django-autotranslate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/lw/n4rl9vm16t38zzv2x_kl74xc0000gn/T/pip-pip-egg-info-rcg342li
         cwd: /private/var/folders/lw/n4rl9vm16t38zzv2x_kl74xc0000gn/T/pip-install-y2vmq72u/django-autotranslate/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lw/n4rl9vm16t38zzv2x_kl74xc0000gn/T/pip-install-y2vmq72u/django-autotranslate/setup.py", line 25, in <module>
        requirements = [str(ir.req) for ir in install_requirements]
      File "/private/var/folders/lw/n4rl9vm16t38zzv2x_kl74xc0000gn/T/pip-install-y2vmq72u/django-autotranslate/setup.py", line 25, in <listcomp>
        requirements = [str(ir.req) for ir in install_requirements]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It is failing when installing via pip 20.1
This issue seems to be related https://github.com/pypa/pip/issues/8188

**Comment by santteegt** [comment]
@cosmosgenius 

That's right!. pip 20.1 introduces some breaking changes. Instead of using `InstallRequirement` class with `req` property (until pip==20.0.2),  it now uses creates a `ParsedRequirement` object with `requirement` as underlying property.

The following line should be changed:

https://github.com/ankitpopli1891/django-autotranslate/blob/45d49f97ad9e6e84eec0baf0b7432884c890ded5/setup.py#L25

**Comment by iamonuwa** [comment]
Downgrading to 9.0.3 works https://stackoverflow.com/a/51153611

**Comment by ankitpopli1891** [comment]
Thanks to @santteegt for sending the PR with the fix!

Closing this issue as it has been released https://github.com/ankitpopli1891/django-autotranslate/releases/tag/v1.1.1
